# Generated by Django 3.2.7 on 2021-09-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('id_no', models.CharField(max_length=13)),
                ('abilities', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=500)),
                ('interests', models.CharField(max_length=500)),
                ('hobbies', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
